### ISSUE TITLE
Stocktake gel

### ISSUE THREAD

**Issue by wjdp** [newtheatre/lx#2]
Count what we have, update [gels.yml](https://github.com/newtheatre/lx/blob/gh-pages/_data/gels.yml)

**Comment by nhyty** [comment]
only if someone will help @wjdp

**Comment by wjdp** [comment]
yeh probs, some point next week/after website meeting?

**Comment by nhyty** [comment]
Works for me, will try and rope another couple of people in too :)

**Comment by nhyty** [comment]
@wjdp, you have the data, please post it here or in the repo properly

**Comment by wjdp** [comment]
I'm going to write a script to make input not take ages

**Comment by nhyty** [comment]
right, enjoy

**Comment by wjdp** [comment]
bc07f1b Data inputted, does nothing useful yet
