### ISSUE TITLE
Colours that don't exist

### ISSUE THREAD

**Issue by wjdp** [newtheatre/lx#8]
![image](https://cloud.githubusercontent.com/assets/1690934/12752180/2191f61e-c9b9-11e5-8433-24bd63503b27.png)

Rosco ones just need manually adding but the Lee ones do not exist on their site.

**Comment by BenWoodford76** [comment]
Looking today this appears to have been fixed

**Comment by BenWoodford76** [comment]
Still need to add descriptions for Rosco Filters, I'll do that Tomorrow
